### ISSUE TITLE
Topic Vector for large text files

### ISSUE THREAD

**Issue by imshashwataggarwal** [askerlee/topicvec#10]
Hi,
I have a large text file of about 2GB from which I want to form topic vector and visualize them through topic clouds. I wanted to ask which file should I use to generate topic vectors.
Another Question I want to ask is can I Generate topic vector using a CSV file having words and their counts across all documents?

Thanks

**Comment by askerlee** [comment]
Sorry for the late reply.
You could use file2topic.py, which takes a single document as input. 

Yeah of course you could generate topic vectors from word frequency files, as the word order is irrelevant. But you need to change quite a lot of code to directly take word frequencies as the input. A simple workaround is to "unfold" a word w that appears N times to w w ... w (N times) before feeding the document to file2topic.py.

**Comment by imshashwataggarwal** [comment]
Thank you for your answer !
